# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/python-poetry/poetry
    # Hooks from https://python-poetry.org/docs/pre-commit-hooks/
    rev: '1.8.1'
    hooks:
    -   id: poetry-check
    -   id: poetry-lock
